### ISSUE TITLE
Register number of bytes instead of number of elements sent

### ISSUE THREAD

**Issue by afarah1** [schnorr/akypuera#24]
Currently Akypuera registers the number of *elements* sent instead of the number of bytes sent. E.g.

````                                            
if (!rank) {                                                                  
  MPI_Recv(&cbuff, 1, MPI_CHAR, MPI_ANY_SOURCE, 0, MPI_COMM_WORLD, MPI_STATUS_IGNORE);
  MPI_Recv(&ibuff, 1, MPI_INT, MPI_ANY_SOURCE, 0, MPI_COMM_WORLD, MPI_STATUS_IGNORE);
} else {                                                                      
  MPI_Send(&cbuff, 1, MPI_CHAR, 0, 0, MPI_COMM_WORLD);                        
  MPI_Send(&ibuff, 1, MPI_INT, 0, 0, MPI_COMM_WORLD);                         
}                                                                             
````

is registered as (`pj_dump`ed)

````
Link, root, LINK, 0.000020, 0.000060, 0.000040, PTP, rank1, rank0, 0, 1
Link, root, LINK, 0.000043, 0.000062, 0.000019, PTP, rank1, rank0, 1, 1
````

The last column is the number of elements sent (1 char, 1 int).

Wouldn't registering the amount of bytes sent (as I thought was already done) more informative for the user? If I'm analysing a trace generated with Akypuera I probably don't know what data type each communication is sending and the "number of elements" information is meaningless. I can write a patch for this if the change is desirable.

**Comment by schnorr** [comment]
@afarah1 I agree with you that the number of bytes is much more important than the number of elements when tracing the message operation. If you can provide us a pull request, that would be great.

**Comment by afarah1** [comment]
I implemented this on 89d029b0ad6eecbe9138cac2ac0b60fe265ad368, but I implemented it for everything there is on afarah1/master. That is, for all new routines added by currently open pull requests:

https://github.com/schnorr/akypuera/pull/23
https://github.com/schnorr/akypuera/pull/25
https://github.com/schnorr/akypuera/pull/26

I tried to do these pull requests as independently as possible, but I think you'd have to merge them in order for things not to break.

I can see two alternatives:

1. Review and merge all currently open pull requests, then I clone schnorr/master and cherry-pick the changes related to this issue and open a new pull request
2. Review and accept a pull request from afarah1/master, which pulls in a lot of commits already merged into schnorr/master for some reason

I think alternative 2. is the easier for both of us, though I think it would mess up the git history a bit.

**Comment by afarah1** [comment]
I added libpoti as a submodule (and all changes that had to be made to aky for it to work) on afarah1/master. Notice that I can't create a (clean) pull request for that unless you do 1. from the comment above (alternatively, https://github.com/schnorr/akypuera/pull/27 contains the "libpoti as submodule" changes as well).

**Comment by afarah1** [comment]
Done
